"use strict";
const startImgUrl = "/static/images/start.png";
const endImgUrl = "/static/images/end.png";
const carImgUrl = "/static/images/car.png";
const driver = "/static/images/driver.png";
const _imports_0 = "/static/images/logo.png";
exports._imports_0 = _imports_0;
exports.carImgUrl = carImgUrl;
exports.driver = driver;
exports.endImgUrl = endImgUrl;
exports.startImgUrl = startImgUrl;
